Criação do schema tracking-api
maplink/sdk-java pull request #18
Opened 2022-11-23 21:42 UTC by PabloaRuiz

- Criação do do schema tracking-api

2022-11-23 22:01 UTC, cleciusjm requested changes
O arquivo application.properties não tem porque existir neste projeto

2022-11-23 22:01 UTC, cleciusjm commented
O build parece ter quebrado também, legal avaliar qual erro que ocorreu neste caso

2022-11-23 22:36 UTC, ROMBARROS commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +
linha em branco

2022-11-24 11:54 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/exceptions/ErrorType.java
> +public enum ErrorType {
Eu acho que funciona bem, podemos começar assim, e depois ir melhorando. O que acha ?

2022-11-24 11:55 UTC, RafaelSTelles commented on tracking-schema/src/test/resources/jsonTracking/order.json
> +  "totalValue": {
O `totalValue` e `estimatedArrival` não são obrigatórios, acho bom criar um caso de teste para isso.

2022-11-24 11:56 UTC, RafaelSTelles commented on tracking-schema/src/test/resources/jsonTracking/order.json
> +    "zipCode": "88304250"
Em origin e destination, precisa também da lat/lng

2022-11-24 11:56 UTC, RafaelSTelles commented on tracking-schema/src/test/resources/jsonTracking/order.json
> +  "expiresIn": "2022-11-28T16:00:00.120Z"
Acho legal também criar um caso de teste onde é informado o tema.

2022-11-24 11:57 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/OrderStatus.java
> +    private final Value value;
O que é esse `Value` ?

2022-11-24 11:58 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Order.java
> +import lombok.*;
Eu não acho uma boa esse padrão de `import *`. Acho que não precisamos mudar, mas podemos melhorar essa convenção para o futuro. cc @cleciusjm

2022-11-24 11:58 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +        if (color == null) throw new TrackingException(ErrorType.TRACKING_01);
Vc valida só a cor, não é bom validar todos os campos obrigatórios ?

2022-11-24 11:59 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/OrderStatus.java
> +    private final Value value;
Esquece, tava confundindo com outra coisa.

2022-11-24 11:59 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/exceptions/ErrorType.java
> +    TRACKING_02("color is incorrect");
Seguindo o padrão, o `c` do Color deveria ser upper case.

2022-11-24 12:02 UTC, cleciusjm commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Order.java
> +import lombok.*;
Pessoalmente gosto do .* em alguns casos, o intellij tem um padrão de usar ele quando há muitos imports do mesmo package, talvez manter o padrão que o intellij já usa possa ser o ideal.

2022-11-24 12:03 UTC, cleciusjm commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/exceptions/ErrorType.java
> +public enum ErrorType {
Eu sempre sou mais fã de tipagem, mas podemos achar um meio termo, ter uma `TrackingValidationException` e um `ValidationErrorType` e nomes de enum mais significativos pode ser uma boa

2022-11-24 12:31 UTC, ROMBARROS commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +    private final String id;
Não seria bom mudar o nome do atributo "id" para "themeId", para evitar confundir com o id do Mongo quando estiver persistido?

2022-11-24 12:36 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +    private final String id;
No meu ponto de vista não, porque de fato é o id, isso tratamos na conversão do schema para entidade.

2022-11-24 13:34 UTC, PabloaRuiz commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +        if (color == null) throw new TrackingException(ErrorType.TRACKING_01);
Claro, vou validar todos os campos obrigatórios é que eu me apeguei muito em validar o hexadecimal e acabei deixando passar. No caso do Theme somente o Id é obrigatório, você melhor criar um método para validar cada campo ou deixar esse validate mesmo ?

2022-11-24 13:38 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +        if (color == null) throw new TrackingException(ErrorType.TRACKING_01);
Esse validade validar todos os campos.

2022-11-24 13:42 UTC, PabloaRuiz commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Order.java
> +import lombok.*;
@cleciusjm, se eu não estou enganado tem como configurar o padrão de import no intellij não tem ? A gente poderia usar essa config para padronizar.

2022-11-24 13:45 UTC, PabloaRuiz commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +    public static final String patternRegex = "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$";
Esse eu deixei passar mesmo, vlw

2022-11-24 15:00 UTC, PabloaRuiz commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +    private final String id;
@RafaelSTelles, podemos fazer o tratamento utilizando os dto também né ?

2022-11-24 15:01 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +    private final String id;
Não, no DTO é como o cliente final obter os dados da nossa API, aqui mantemos como `id` mesmo.

2022-11-24 15:40 UTC, ROMBARROS commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Theme.java
> +    private final String id;
É que embora seja um identificador para o usuário, não será o identificador (id) para o Mongo, então quando persistirmos no Mongo existirão dois ids esse que era "name" e o id mesmo do Mongo....eu achei que poderia causar confusão.

2022-11-24 18:30 UTC, felipemendes-maplink commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/exceptions/ErrorType.java
> +public enum ErrorType {
Uma coisa que eu acho legal de refatorar nesse enum, seria ao inves de ter TRACKING_01, que esta bem generico, seria usar algo mais especifico. Ex. ErrorType.COLOR_NULL, ErrorType.COLOR_HEX_INVALID.
Acho que fica mais facil de saber que eh mais ou menos a mensagem do erro.

2022-11-24 18:30 UTC, felipemendes-maplink commented on tracking-schema/src/test/java/global/maplink/tracking/schema/schemaTest/OrderTest.java
> +
Tem umas linhas em branco aqui

2022-11-24 19:00 UTC, cleciusjm commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/exceptions/ErrorType.java
> +public enum ErrorType {
Isso mesmo, o ValidationErrorType seria o seu ErrorType, mas concentrando apenas erros de validação

2022-11-24 19:01 UTC, cleciusjm commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Order.java
> +import lombok.*;
@felipemendes-maplink na verdade não, a linkagem da compilação da JVM é feita sob demanda, importar tudo não agrega peso ou complexidade ao código, só uma definição de leitura, a não ser q vc use tudo, nem tudo será incluida na linkagem

2022-11-25 14:39 UTC, RafaelSTelles commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Order.java
> +        return Objects.isNull(value) || value.trim().isEmpty();
`value.isBlank` já aplica o `trim`

2022-11-25 19:18 UTC, PabloaRuiz commented on tracking-schema/src/main/java/global/maplink/tracking/schema/schema/domain/Order.java
> +        return Objects.isNull(value) || value.trim().isEmpty();
Os `isBlank` está disponível na versão do java 11 ou superior. No Sdk usamos o java 8.

2022-11-25 20:44 UTC, cleciusjm approved these changes

2022-11-25 20:48 UTC, merged