Splt 1670 migrar chamadas store locator para place
maplink/sdk-java pull request #43
Opened 2023-04-12 19:58 UTC by ROMBARROS

Alterações para incluir os novos métodos para listar states, cities e districts  e para os novos filtros por state, city, district, tags, geofence (center e radius).

2023-04-12 20:09 UTC, cleciusjm requested changes
Faltou os testes, no SDK todos os métodos tem testes implementados

2023-04-12 20:09 UTC, cleciusjm commented on place-schema/src/main/java/global/maplink/place/schema/ListAllDistrictsRequest.java
> +    public final String path = "place/v1/places/state/" + state + "/city/" + city + "/districts";
acho q isso vai quebrar, já que a URL precisa de encode tipo /state/SP/city/São Paulo/districts não é uma url válida

2023-04-12 20:09 UTC, cleciusjm commented on place-schema/src/main/java/global/maplink/place/schema/ListAllPlacesRequest.java
> +    private final String center;
poderia usar tipos mais especificos:
 - tags: lista de strings
 - center: MaplinkPoint
 - radius: numerico

2023-04-12 20:09 UTC, cleciusjm commented on place-schema/src/main/java/global/maplink/place/schema/ListAllCitiesRequest.java
> +    public final String path = "place/v1/places/state/" + state + "/cities";
ao invés de concatenar, poderia usar template e string.format, além de ser legal validar se algo foi passado pro state

2023-04-12 20:09 UTC, cleciusjm commented on .idea/jpa-buddy.xml
acho q não precisa desse arquivo

2023-04-12 20:09 UTC, cleciusjm commented on place-schema/src/main/java/global/maplink/place/schema/ListAllCitiesRequest.java
> +    public final String path = "place/v1/places/state/" + state + "/cities";
também acho q não precisa ser publico esse campo...

2023-04-12 20:09 UTC, cleciusjm commented on place-schema/src/main/java/global/maplink/place/schema/ListAllDistrictsRequest.java
> +    private final String state;
adicionar validações aqui tbm

2023-04-12 20:09 UTC, cleciusjm commented on place-schema/src/main/java/global/maplink/place/schema/ListAllDistrictsRequest.java
> +    public Function<Response, PlacePageResult> getResponseParser(JsonMapper mapper) {
Imagino que o retorno não seja um PlacePageResult aqui né

2023-04-12 20:10 UTC, cleciusjm commented
O build parece estar quebrando tbm, chegou a construir um `mvn clean package` local?

2023-04-12 20:14 UTC, ROMBARROS commented on place-schema/src/main/java/global/maplink/place/schema/ListAllDistrictsRequest.java
> +    public Function<Response, PlacePageResult> getResponseParser(JsonMapper mapper) {
opa, tem razão, não é, vou alterar...obrigado.

2023-04-12 20:15 UTC, cleciusjm commented on place-schema/src/main/java/global/maplink/place/schema/ListAllDistrictsRequest.java
> +    public Function<Response, PlacePageResult> getResponseParser(JsonMapper mapper) {
isso teria pegado nos testes

2023-04-12 20:18 UTC, ROMBARROS commented on place-schema/src/main/java/global/maplink/place/schema/ListAllPlacesRequest.java
> +    private final String center;
mas não tem de ser do mesmo tipo que está lá no endpoint da place-api?

2023-04-12 20:19 UTC, ROMBARROS commented on place-schema/src/main/java/global/maplink/place/schema/ListAllCitiesRequest.java
> +    public final String path = "place/v1/places/state/" + state + "/cities";
sim, farei assim...valeu pela dica

2023-04-12 20:20 UTC, ROMBARROS commented on .idea/jpa-buddy.xml
vixe!! não sei de onde ele veio....deve ter sido o meu IntelliJ que gerou né?

2023-04-12 20:20 UTC, ROMBARROS commented on place-schema/src/main/java/global/maplink/place/schema/ListAllDistrictsRequest.java
> +    private final String state;
ok, vou adicionar ;-)

2023-04-12 20:24 UTC, ROMBARROS commented on place-schema/src/main/java/global/maplink/place/schema/ListAllDistrictsRequest.java
> +    public final String path = "place/v1/places/state/" + state + "/city/" + city + "/districts";
Não entendi. Lá na linha 27 ele não vai colocar a String pronta como argumento "path" ? 
return get(environment.withService(path));

2023-04-12 20:27 UTC, ROMBARROS commented on place-schema/src/main/java/global/maplink/place/schema/ListAllDistrictsRequest.java
> +    public Function<Response, PlacePageResult> getResponseParser(JsonMapper mapper) {
sim, eu deveria ter rodado o comando mvn clean package e pegaria né? Foi mal, não me esquecerei mais mestre eheheh

2023-04-12 21:18 UTC, rafaelstelles commented on place/src/main/java/global/maplink/place/sync/PlaceSyncApiImpl.java
> +    public List<String> listAllStates(ListAllStatesRequest request) {
Não deveria ter testes também ?

2023-04-13 13:36 UTC, ROMBARROS commented on place/src/main/java/global/maplink/place/sync/PlaceSyncApiImpl.java
> +    public List<String> listAllStates(ListAllStatesRequest request) {
Opa, como os demais métodos legados (listAll, create, getByOriginId) dessa classe também não tinham testes, eu entendi que não deveria, mas concordo que seria bom ter então vou implementar os testes. Obrigado pelo aviso.

2023-04-18 19:30 UTC, rafaelstelles commented on core/src/main/java/global/maplink/commons/PageResult.java
> +import static java.util.Collections.emptyList;
O impot ficou mto junto

2023-04-18 19:30 UTC, rafaelstelles commented on place-schema/src/main/java/global/maplink/place/schema/ListAllPlacesRequest.java
> +            request = request.withQuery("center", String.format(Locale.ENGLISH, "%f,%f", center.getLatitude(), center.getLongitude()));
Eu acho que não precisa do Locale

2023-04-18 19:31 UTC, ROMBARROS commented on place-schema/src/main/java/global/maplink/place/schema/ListAllPlacesRequest.java
> +            request = request.withQuery("center", String.format(Locale.ENGLISH, "%f,%f", center.getLatitude(), center.getLongitude()));
para evitar dele usar virgula em vez de ponto decimal

2023-04-18 19:31 UTC, rafaelstelles commented on place/src/test/java/global/maplink/place/utils/TestPlaceUtils.java
> +    public Place testPlaceCreator(String name, String id, String state, String city, String district) {
Como a classe não tem estado, ela pode ser estática, assim fica menos verboso o código.

2023-04-18 19:32 UTC, rafaelstelles commented on place/src/test/java/global/maplink/place/sync/PlaceSyncApiTest.java
> +    @Order(1)
Porque precisou da order ?

2023-04-18 19:32 UTC, rafaelstelles commented on place/src/test/java/global/maplink/place/sync/PlaceSyncApiTest.java
> +            System.out.println("districtsResulted -->> " + districtsResulted.toString());
Não deveria ter o system.out né ?

2023-04-18 19:35 UTC, ROMBARROS commented on place/src/test/java/global/maplink/place/sync/PlaceSyncApiTest.java
> +    @Order(1)
para garantir que os testes 2 em diante rodem depois do 1 que não podia ser com beforeall

2023-04-18 19:37 UTC, PabloaRuiz commented on place/src/test/java/global/maplink/place/async/PlaceAsyncApiTest.java
> +            System.out.println("districtsResulted -->> " + districtsResulted.toString());
@ROMBARROS, qual a ideia do System.out aqui ?

2023-04-18 19:43 UTC, PabloaRuiz commented on place/src/test/java/global/maplink/place/utils/TestPlaceUtils.java
> +                .subCategory(SubCategory.POSTOS_DE_COMBUSTIVEL)
Como você fez um import static no category, poderia padronizar e fazer no subCategory

2023-04-18 19:46 UTC, PabloaRuiz commented on place/src/test/java/global/maplink/place/utils/PlaceSampleFiles.java
> +    PLACE_SP1("place.json/place_SP1.json"),
@ROMBARROS, se o arquivo `json` é o mesmo qual a necessidade dos três ? Já que eles estão repetindo a mesma informação ?

2023-04-18 19:52 UTC, PabloaRuiz commented on place/src/test/java/global/maplink/place/sync/PlaceSyncApiTest.java
> +    @Order(1)
Você poderia utilizar o `order`  no teste que você tem prioridade, e a partir dele deixar a ordem aleatória ?

2023-04-18 21:01 UTC, ROMBARROS commented on place/src/test/java/global/maplink/place/async/PlaceAsyncApiTest.java
> +            System.out.println("districtsResulted -->> " + districtsResulted.toString());
sobrou de quando eu estava implementando e debugando...vou deletar eheh

2023-04-18 21:01 UTC, ROMBARROS commented on place/src/test/java/global/maplink/place/utils/TestPlaceUtils.java
> +                .subCategory(SubCategory.POSTOS_DE_COMBUSTIVEL)
boa

2023-04-18 21:12 UTC, ROMBARROS commented on place/src/test/java/global/maplink/place/utils/PlaceSampleFiles.java
> +    PLACE_SP1("place.json/place_SP1.json"),
esse Enum era para ter sido deletado, obrigado pelo aviso

2023-04-18 21:15 UTC, ROMBARROS commented on place/src/test/java/global/maplink/place/utils/TestPlaceUtils.java
> +    public Place testPlaceCreator(String name, String id, String state, String city, String district) {
ok, tem razão, vou mudar...valeu a dica.

2023-04-19 18:16 UTC, ROMBARROS commented on place/src/test/java/global/maplink/place/utils/TestPlaceUtils.java
> +                .subCategory(SubCategory.POSTOS_DE_COMBUSTIVEL)
Então, o IntelliJ reclamou pois ambos ficam apenas como POSTOS_DE_COMBUSTIVEL então deixei assim mesmo

2023-04-19 19:10 UTC, felipemendes1994 commented on place/src/test/java/global/maplink/place/async/PlaceAsyncApiTest.java
> +    @Order(1)
Porque ta usando essa anotacao @Order? Precisa de uma sequencia especifica para os testes rodarem?

2023-04-19 19:10 UTC, felipemendes1994 commented on place/src/test/java/global/maplink/place/sync/PlaceSyncApiTest.java
> +    @Order(1)
@ROMBARROS, mas voce "desenhou" os testes para ser assim e meio que dependerem um do outro? Ou eh algum outro problema?

2023-04-19 19:10 UTC, felipemendes1994 commented on .idea/misc.xml
Precisa desse arquivo no projeto?

2023-04-19 20:07 UTC, ROMBARROS commented on place-schema/src/main/java/global/maplink/place/schema/PlacePageResult.java
> +    public PlacePageResult() {}
Sim precisa, eheh estava quebrando sem ele.

2023-04-19 20:15 UTC, ROMBARROS commented on place/src/test/java/global/maplink/place/async/PlaceAsyncApiTest.java
> +    @Order(1)
sim, preciso garantir que os places sejam criados antes, mas não pode ser num beforeAll

2023-04-19 20:19 UTC, ROMBARROS commented on .idea/jpa-buddy.xml
Não sei o que é esse arquivo...não me lembro de ter visto ele ao examinar a aba de Commit do IntelliJ one vejo os arquivos que mudaram antes de commitar...acho que o IntelliJ acrescentou ele

2023-04-19 20:50 UTC, ROMBARROS commented on .idea/misc.xml
Pensei em dar um git ignore nele, mas não vai resolver pois esse arquivo já existia na atual versão de Prod e o .gitignore only ignores newly added (untracked) files.

If you have files that have already been added to the repository, all their changes will be tracked as usual, even if they are matched by .gitignore rules.

2023-04-20 12:12 UTC, felipemendes1994 commented on .idea/jpa-buddy.xml
Por estar dentro do diretorio .idea, parece que ele nao vai ter utilidade para o projeto em si. Eh mais algo relacionado as configs da sua IDE.

Se voce quiser confirmar, pega o arquivo, recorta, coloca em outro diretorio e roda um `mvn clean package`. Se rodar sem erros, entao nao precisa dele.

2023-04-20 12:13 UTC, felipemendes1994 commented on .idea/misc.xml
Se esse arquivo ja estava, entao pode desconsiderar o comentario.

2023-04-20 12:13 UTC, ROMBARROS commented on .idea/jpa-buddy.xml
ah , saquei....vou fazer esse teste então...valeu

2023-04-20 12:29 UTC, ROMBARROS commented on .idea/jpa-buddy.xml
@felipemendes1994 nesse teste que você sugeriu, se eu recortar e colar num diretório externo ao projeto e rodar os testes todos e passar já basta para saber que não precisa do arquivo certo?

2023-04-20 12:43 UTC, cleciusjm approved these changes
Algumas alterações de teste apenas, para evitar fragilidade dos mesmos

2023-04-20 12:43 UTC, cleciusjm commented on place/src/test/java/global/maplink/place/sync/PlaceSyncApiTest.java
> +    @Order(1)
Acho q a ideia é que esse teste além de garantir o estado base pros outros testes, também valida o create, em um beforeAll um assertion quebrado não dá um indicativo claro, contrário a um teste, onde vai sinalizar como teste quebrado e indicar o ponto correto de checagem, tanto em stacktraces quanto em reports de cobertura

2023-04-20 12:43 UTC, cleciusjm commented on place/src/test/java/global/maplink/place/sync/PlaceSyncApiTest.java
> +            assertThat(citiesResulted).contains("Santos");
poderia ser um unico contains com ambos

2023-04-20 12:43 UTC, cleciusjm commented on place/src/test/java/global/maplink/place/sync/PlaceSyncApiTest.java
> +            assertThat(districtsResulted.toString()).contains(LIST_ALL_DISTRICTS_EXPECTED_RESULT);
o `.toString()` aqui é desnecessário e fragiliza o teste, dá pra usar o contais do assertThat direto, como nos testes anteriores.

2023-04-20 12:43 UTC, cleciusjm commented on place/src/test/java/global/maplink/place/sync/PlaceSyncApiTest.java
>      void mustFailWithInvalidCredentials() {
esses testes de falha, que não dependem do estado, não precisam do order

2023-04-20 12:43 UTC, cleciusjm commented on place/src/test/java/global/maplink/place/utils/TestPlaceUtils.java
> +    public static final String LIST_ALL_DISTRICTS_EXPECTED_RESULT = "[José Menino]";
aqui poderia ser uma string ou uma lista de strings com um elemento apenas, como na constante acima

2023-04-20 12:43 UTC, cleciusjm commented on place/src/test/java/global/maplink/place/utils/TestPlaceUtils.java
> +        Set<String> tags = new HashSet<>();
poderia usar direto o .tag do builder do place

2023-04-20 20:41 UTC, felipemendes1994 commented on .idea/jpa-buddy.xml
Sim

2023-04-20 20:42 UTC, felipemendes1994 approved these changes

2023-04-24 12:24 UTC, merged