feat: [SPLT-2204] Adiciona schema da planning
maplink/sdk-java pull request #61
Opened 2024-06-24 13:30 UTC by guipia15

2024-06-24 13:52 UTC, felipemendes1994 requested changes

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Callback.java
> +
Linha sobrando aqui

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/CalculationMode.java
> +    private CalculationMode(){
Como ja tem anotado @NoArgsConstructor, nao precisa da declaracao desse construtor. E o force=true,pode remover tambem.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Activity.java
> +public class Activity {
Faltou colocar os campos dessa classe como final.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Compartment.java
> +    private final String type = CompartmentType.FIXED.toString();
Fica legal adicionar um import static nesse CompartmentType.FIXED.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Coordinates.java
> +
Linha sobrando

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/CompartmentSolutionGroup.java
> +
Linha sobrando.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/IncompabilityRelationship.java
> +
Linha sobrando

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LogisticZoneType.java
> +
Linha sobrando, e identacao ta errada.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/OptimizationType.java
> +
Linha sobrando

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ProblemTrip.java
> +
linha sobrando

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Route.java
> +
linha sobrando

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Vehicle.java
> +
linha sobrando

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/VehicleRoute.java
> +
linha sobrando.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ViolationConstraint.java
> +
linha sobrando.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Activity.java
> +
linha sobrando.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/ActivityType.java
> +
linha sobrando.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/CompartmentSolution.java
> +
linha sobrando.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/CompartmentSolutionGroup.java
> +
linha sobrando

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/PossibleCauseRejectGroup.java
> +public class PossibleCauseRejectGroup {
linha sobrando.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Route.java
> +
linha sobrando.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Solution.java
> +
linha sobrando.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/CompartmentConfiguration.java
> +    private final Compartment[] compartments;
Aqui pode ser alterado para utilizar uma list ao inves de array de compartment.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/IncompatibilityType.java
> +public class IncompatibilityType {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LogisticZoneType.java
> +public class LogisticZoneType {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/OperationStatus.java
> +public class OperationStatus {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/OptimizationType.java
> +public class OptimizationType {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/PositionInRoute.java
> +public class PositionInRoute {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/PositionInTimeWindow.java
> +public class PositionInTimeWindow {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/SolutionToRebuild.java
> +    private final String optimizationType = OptimizationType.CUSTOM;
Fica legal adicionar um import static neste cara.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/ActivityType.java
> +public class ActivityType {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/PositioningType.java
> +public class PositioningType {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum.

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/RouteStatus.java
> +public class RouteStatus {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum

2024-06-24 13:52 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/SequenceType.java
> +public class SequenceType {
Essa classe basicamente armazena valores constantes, entao pode ser modificada para ser um enum.

2024-06-24 13:57 UTC, franccr requested changes

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Callback.java
> +
espaço sobrando aqui

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Compartment.java
> +    private final String name;
nas outras classes você separou com espaço as variaveis e aqui você deixou juntas. Qual padrão irá manter?

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Compartment.java
> +    private final String type = CompartmentType.FIXED.toString();
poderia rolar um import aqui.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Coordinates.java
> +
espaço aqui sobrando

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/IncompabilityRelationship.java
> +
espaço sobrando aqui.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/IncompatibilityType.java
> +	public static final String ORDERED = "ORDERED";
formação diferente das outras classes.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LogisticZoneType.java
> +	public static final String PRIORITARY = "PRIORITARY";
formatação diferente.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/OperationStatus.java
> +
formatação diferente.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/OptimizationType.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/PositionInRoute.java
> +
formatação diferente.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/PositionInTimeWindow.java
> +
formatação diferente.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ProblemResponse.java
> +	private static String id;
formatação diferente.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ProblemTrip.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Product.java
> +@Builder
esse builder poderia ficar abaixo do data.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Route.java
> +
espaço sobrando

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Site.java
> +@Builder
builder pode ficar abaixo do data

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/SolutionToRebuild.java
> +@Builder
faltou um expaço entre anotação e o builder pode ficar abaixo do data.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Vehicle.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/VehicleRoute.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/VehicleType.java
> +@Builder
builder poderia ficar abaixo do data.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ViolationConstraint.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Activity.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/ActivityType.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/CompartmentSolution.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/CompartmentSolutionGroup.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/PossibleCauseRejectGroup.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Route.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Solution.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Solution.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Solution.java
> +
espaço sobrando.

2024-06-24 13:57 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Solution.java
> +    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
aqui poderia rolar um import

2024-06-26 14:18 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Activity.java
> +    public List<String> getOperations() {
Esse get acho que da pra remover.

2024-06-26 14:18 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ProblemResponse.java
> +	private static String id;
Este campos ainda esta com a identacao errada.

2024-06-26 14:18 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Product.java
> +    private final String[] packagings;
Aqui poderia alterar para um lista de Strings ao inves de manter um array.

2024-06-26 14:18 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/SolutionToRebuild.java
> +    private final String optimizationType = CUSTOM.toString();
Aqui nao pediu pra adicionar a anotacao @Builder.Default?

2024-06-26 14:18 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ViolationConstraint.java
> +@Builder
Como essa classe so tem um campo talvez nao faca sentido utilizar o builder.

2024-06-26 17:42 UTC, franccr requested changes

2024-06-26 17:42 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Vehicle.java
> +@Builder
Faltou ajustar essa anotação

2024-06-26 17:42 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ProblemTrip.java
> +@Builder
Fat,ou ajustar essa anotação

2024-06-26 17:42 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Operation.java
> +@Builder
Faltou ajustar essa anotação

2024-06-26 17:42 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LogisticZone.java
> +@Builder
Faltou ajustar essa anotação

2024-06-26 17:42 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LogisticConstraint.java
> +@Builder
Faltou ajustar anotação

2024-06-26 17:42 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LegislationProfile.java
> +@Builder
Faltou ajustar essa anotação

2024-06-26 17:42 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/IncompabilityRelationship.java
> +@Builder
Faltou ajustar essa anotação

2024-06-26 17:42 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Compartment.java
> +@Builder
Ficou invertida essa anotação

2024-06-26 17:42 UTC, franccr commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Callback.java
> +@Builder
Faltou ajustar essa anotação

2024-06-26 18:02 UTC, PabloaRuiz commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ProblemTrip.java
> +public class ProblemTrip {
só faltou um `Ctrl + Alt + L` para corrigir os espaços.

2024-06-26 18:17 UTC, PabloaRuiz commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ProblemTrip.java
> +public class ProblemTrip {
só faltou um `Ctrl + Alt + L` para corrigir os espaços.

2024-06-26 18:17 UTC, PabloaRuiz commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/SolutionToRebuild.java
> +    private final String optimizationType = CUSTOM.toString();
Porque `String` e não o `Enum` do OptimizationType ?

2024-06-26 18:17 UTC, PabloaRuiz commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Compartment.java
> +    private final String type = FIXED.toString();
Porque `String` e não o `Enum` do CompartmentType ?

2024-06-26 18:48 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Callback.java
> +@AllArgsConstructor
Adiciona o access level private nesse tambem.

2024-06-26 18:48 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Compartment.java
> +    private final String[] allowedPackagings;
Troca esse array por lista.

2024-06-26 18:48 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/Activity.java
> +public class Activity {
Existem duas classes com o mesmo nome, e exatamente os mesmos campos. Vale a pena remove essa do pacote solution, e utilizar a do pacote da problem. Caso de algum erro de import, atualizar o import pro pacote da problem, tambem.

2024-06-26 18:48 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ViolationConstraint.java
> +public class ViolationConstraint {
Nessas classes que so tem um campo, que removeu o @builder, precisa remover o access = PRIVATE, senao o usuario nao vai conseguir instanciar objetos validos.

2024-06-26 18:48 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/IncompabilityRelationship.java
> +@AllArgsConstructor
Adicionar o access = PRIVATE nesse cara tambem

2024-06-26 18:48 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/solution/ViolationConstraint.java
> +@AllArgsConstructor(access = PRIVATE)
Remover o @Builder e access = PRIVATE

2024-06-26 18:52 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/SolutionToRebuild.java
> +    private final String optimizationType = CUSTOM.toString();
Feito, obrigado

2024-06-26 18:52 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Compartment.java
> +    private final String type = FIXED.toString();
Feito tambem, obrigado

2024-06-26 19:05 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/ProblemTrip.java
> +public class ProblemTrip {
Resolvido

2024-06-26 20:47 UTC, ROMBARROS commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Activity.java
> +    private final String type;
esse type é um String mesmo?

2024-07-03 15:15 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Activity.java
> +    private final String type;
no planning-api esta como um String

2024-07-04 14:28 UTC, felipemendes1994 requested changes

2024-07-04 14:28 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/IncompabilityRelationship.java
> +    private final String type;
Esse campo pode ser alterado de String para o enum IncompatibiltyType

2024-07-04 14:28 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LegislationProfile.java
> +public class LegislationProfile {
Na classe original dentro do projeto planning-api, tem alguns comentarios para esses campos. Por ser uma especie de documentacao nossa, acho interessante adicionar eles aqui tambem.

2024-07-04 14:28 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LogisticZone.java
> +    private final String zonePriority;
Esse campo pode ser alterado de String para o enum LogisticZoneType

2024-07-04 14:28 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Operation.java
> +    private final String type;
Esse campo pode ser alterado de String para o enum OperationType

2024-07-04 14:28 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Operation.java
> +    private final String status;
Esse campo pode ser alterado de String para o enum OperationStatus.

2024-07-04 14:28 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/OptimizationType.java
> +public enum OptimizationType {
Essa classe original na planning-api tem alguns comentarios. Como elas servem como uma especie de documentacao interna, acho interessante replicar aqui.

2024-07-04 14:28 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Problem.java
> +    private final String calculationMode;
Esse campo pode ser alterado de String para o Enum CalculationMode

2024-07-04 14:28 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Problem.java
> +    private final Set<String> restrictionZones;
Nao deu problema a serializacao do json pra set neste campo?

2024-07-04 15:45 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/CompartmentConfiguration.java
> +    private final List<String> compartments;
feito

2024-07-04 15:45 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/IncompabilityRelationship.java
> +    private final String type;
feito

2024-07-04 15:45 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LegislationProfile.java
> +public class LegislationProfile {
feito

2024-07-04 15:45 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/LogisticZone.java
> +    private final String zonePriority;
feito

2024-07-04 15:45 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Operation.java
> +    private final String type;
feito

2024-07-04 15:45 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Operation.java
> +    private final String status;
feito

2024-07-04 15:45 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/OptimizationType.java
> +public enum OptimizationType {
feito

2024-07-04 15:45 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Problem.java
> +    private final Set<String> restrictionZones;
Nao. Os outros Sets que mudamos para Lists tinham valores com campos especificos, como "name": "name1" mas esse soh tem Strings. Aparentement Sets de Strings da certo

2024-07-04 15:45 UTC, guipia15 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Problem.java
> +    private final String calculationMode;
feito

2024-07-09 00:49 UTC, felipemendes1994 requested changes

2024-07-09 00:49 UTC, felipemendes1994 commented on planning-schema/src/test/java/global/maplink/planning/schema/problem/OperationTest.java
> +        assertFalse(operation.getCustomerTimeWindowBlocked());
Aqui da pra usar o `assertThat().isFalse()` tambem

2024-07-09 00:49 UTC, felipemendes1994 commented on planning-schema/src/test/java/global/maplink/planning/schema/problem/ProblemTest.java
> +        assertTrue(problem.getHasSolution());
Existe um metodo `assertThat().isTrue()`. Acho legal usar ele aqui ao inves desse.

2024-07-09 00:49 UTC, felipemendes1994 commented on planning-schema/src/test/java/global/maplink/planning/schema/problem/VehicleTypeTest.java
> +        assertEquals("exemplo1", vehicleType.getName());
Alterar esses assertEquals para assertThat pra seguir o padrao.

2024-07-09 00:49 UTC, felipemendes1994 commented on planning-schema/src/test/java/global/maplink/planning/schema/solution/IndicatorsTest.java
> +        assertThat(indicators.getTollCosts().compareTo(bigDecimalTest)).isZero();
Aqui eu acho que ficaria melhor se voce utilizasse a inicializaca do BigDecimal direto inline. Ficaria assim `assertThat(indicators.getTollCosts().compareTo(BigDecimal.valueOf(19))).isZero();`. Assim da pra tirar esse objeto que cria na linha 39. Como nao eh uma invocacao muito grande, e so eh utilizada uma unica vez. Fica mais estetico no codigo.

2024-07-09 00:49 UTC, felipemendes1994 commented on planning-schema/src/test/java/global/maplink/planning/testUtils/SampleFiles.java
> +    SOLUTION("planning.json/samples/solution/solution.json");
Aqui nos vamos adicionar mais alguns arquivos que serao usados em cenarios de testes que existem la na planning-api. E a tendencia eh essa quantidade de arquivos crescer ainda mais e comecar a ficar um codigo muito extenso aqui. Por conta disso eu tenho alguns sugestoes de coisas que voce pode modificar.
1 - Renomeia esse enum para ProblemSampleFiles
2 - Cria um outro enum, praticamente igual a esse com o nome SolutionSampleFiles.
3 - Faz o mesmo passo acime para as classes do pacote commons. Entao vai ficar uma outra classe CommonsSampleFiles

basicamente vao ter 3 arquivos. Cada uma com arquivos de cada pacote (solution, problem e commons).

Ai voce isola os arquivos de solution dentro do enum de solution, problem no enum de problems e assim por diante. Atualmente estao todos misturados.
Agora pode parecer desnecessario, mas vao ser adicionar muitos outros arquivos de testes, e dessa forma que eu sugeri vai ficar mais organizado.

2024-07-16 13:57 UTC, felipemendes1994 requested changes

2024-07-16 13:57 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/TimeWindow.java
> +        if (isInvalid(String.valueOf(start))) {
O correto aqui seria fazer a validacao de acordo com como esta implementado na planning-api. Nao precisa converter pra String. Eh validar se esta nulo ou nao. E esta faltando a validacao de start e end. Da uma olhada na TimeWindowValidator pra saber como implementar.

2024-07-16 13:57 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/AvailablePeriod.java
> +public class AvailablePeriod {
Falta implementar a validator desse cara. Mas faz a implementacao de acordo com o que ja existe no planning-api na classe AvailablePeriodValidator.

2024-07-16 13:57 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Callback.java
> +public class Callback {
Falta implementar o validator dessa classe.

2024-07-16 13:57 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Vehicle.java
> +public class Vehicle implements Validable {
A validacao nao esta de acordo com a implementacao do VehicleValidator da planning-api

2024-07-16 13:57 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Product.java
> +public class Product implements Validable {
A implementacao da validacao nao esta de acordo com o que esta na planning-api

2024-07-16 13:57 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Compartment.java
> +public class Compartment implements Validable {
A implementacao da validacao nao esta de acordo com o que ja existe na planning-api

2024-07-16 13:57 UTC, felipemendes1994 commented on planning-schema/src/main/java/global/maplink/planning/schema/problem/Problem.java
> +public class Problem implements Validable {
A implementacao da validacao esta diferente do que ja existe na planning-api

2024-07-16 15:19 UTC, felipemendes1994 approved these changes

2024-07-16 17:42 UTC, merged