feat: [SPLT-2252] Validações, jsons, e testes de campos nulos
maplink/sdk-java pull request #69
Opened 2024-08-09 17:08 UTC by guipia15

2024-08-09 19:12 UTC, felipemendes1994 requested changes

2024-08-09 19:12 UTC, felipemendes1994 commented on emission-schema/src/main/java/global/maplink/emission/schema/EmissionRequest.java
> +        return violations;
Antes de retornar as violations, acho legal validar se o fractionedEmission esta nulo, e caso nao esteja, validar ele tambem. Tem as regras dele na EBR

2024-08-09 19:12 UTC, felipemendes1994 commented on emission-schema/src/test/java/global/maplink/emission/schema/EmissionRequestTest.java
> +        assertThat(emissionRequest.validate()).isNotEmpty().hasSize(3);
Acho legal validar os valores dos itens que estao dentro da lista.

2024-08-09 19:12 UTC, felipemendes1994 commented on emission-schema/src/test/java/global/maplink/emission/testUtils/SampleFiles.java
> +    EMISSION_REQUEST_WITH_NULL_GET_AUTONOMY("emission/json/emissionRequestWithNullGetAutonomy.json"),
Acho que esse GET no nome dos arquivos e dos itens do enum ficam um pouco estranho. Eu deixaria tipo: EMISSION_REQUEST_WITH_NULL_FUEL_TYPE. Sem o GET. Ai pode aplicar isso no nome dos arquivos e nos itens do enum.

2024-08-09 19:12 UTC, felipemendes1994 commented on emission-schema/src/test/java/global/maplink/emission/schema/EmissionRequestTest.java
> +    void shouldNotValidateFuelType() {
Esse shouldNotValidate fica um pouco estranho. Seria melhor colocar algo como, shouldValidateFuelTypeNull. Ou algo do tipo. O nome do teste ta dando a entender o contrario do que o metodo realmente faz.

O mesmo serve para os testes de baixo.

2024-08-09 19:12 UTC, felipemendes1994 commented on emission-schema/src/main/java/global/maplink/emission/schema/exception/EmissionUpdateViolation.java
> +public class EmissionUpdateViolation implements ValidationViolation {
Talvez seja necessario repensar o nome dessa classe, porque embora seguindo o padrao. Aqui nao eh uma atualizacao de fato. Sabe? Poderia ser so EmissionViolation. Acho que fica melhor.

2024-08-13 18:28 UTC, felipemendes1994 requested changes

2024-08-13 18:28 UTC, felipemendes1994 commented on emission-schema/src/main/java/global/maplink/emission/schema/EmissionRequest.java
> +            violations.add(EmissionViolation.of("emission.totalDistance"));
Acho interessante devolver um erro diferente caso o total distance seja menor que zero. Na forma que voce modelou atualmente, a violation sempre lanca uma mensagem de campo nao nulo

2024-08-13 18:28 UTC, felipemendes1994 commented on emission-schema/src/main/java/global/maplink/emission/schema/exception/EmissionViolation.java
> +        this.message = String.format("%s: %s", EmissionErrorType.REQUIRED_FIELDS_INVALID.getMessage(), field);
O valor do enum REQUIRED_FIELDS_INVALID esta muito generico. Acho interessante deixar mais especifico pois, existem diferentes cenarios que devem lancar mensagens diferentes. Acho valido lancar mensagens espeficas, e fazer validacoes especificas.

2024-08-13 18:39 UTC, guipia15 commented on emission-schema/src/main/java/global/maplink/emission/schema/EmissionRequest.java
> +            violations.add(EmissionViolation.of("emission.totalDistance"));
feito

2024-08-13 19:38 UTC, franccr requested changes

2024-08-13 19:38 UTC, franccr commented on emission-schema/src/main/java/global/maplink/emission/schema/exception/EmissionErrorType.java
> +
espaço sobrando

2024-08-13 19:52 UTC, guipia15 commented on emission-schema/src/main/java/global/maplink/emission/schema/exception/EmissionViolation.java
> +        this.message = String.format("%s: %s", EmissionErrorType.REQUIRED_FIELDS_INVALID.getMessage(), field);
feito

2024-08-13 19:52 UTC, guipia15 commented on emission-schema/src/main/java/global/maplink/emission/schema/exception/EmissionErrorType.java
> +
feito

2024-08-14 14:05 UTC, felipemendes1994 requested changes

2024-08-14 14:05 UTC, felipemendes1994 commented on emission-schema/src/main/java/global/maplink/emission/schema/EmissionRequest.java
> +        if(!isNull(fractionedEmission)){
Aqui da pra usar stream pra fazer a soma. Toda a logica fica resumida em praticamente uma linha.

2024-08-14 14:15 UTC, franccr requested changes

2024-08-14 14:15 UTC, franccr commented on emission-schema/src/test/java/global/maplink/emission/schema/EmissionRequestTest.java
> +
tem linha sobrando.

2024-08-14 14:15 UTC, franccr commented on emission-schema/src/test/java/global/maplink/emission/schema/EmissionRequestTest.java
> +
tem linha sobrando

2024-08-14 14:15 UTC, franccr commented on emission-schema/src/test/java/global/maplink/emission/schema/EmissionRequestTest.java
> +
tem linha sobrando

2024-08-14 14:23 UTC, guipia15 commented on emission-schema/src/main/java/global/maplink/emission/schema/exception/EmissionViolation.java
> +    public static EmissionViolation of(final String field, EmissionErrorType errorType) {
feito

2024-08-14 14:50 UTC, guipia15 commented on emission-schema/src/main/java/global/maplink/emission/schema/EmissionRequest.java
> +        if(!isNull(fractionedEmission)){
feito

2024-08-14 15:05 UTC, felipemendes1994 approved these changes

2024-08-14 15:08 UTC, franccr approved these changes

2024-08-14 15:09 UTC, merged